
update edition set goldfish_name = mkm_name where code = 'CMD';

update edition set goldfish_name = 'Coldsnap Theme Deck Reprints' where code='CST';
update edition set goldfish_name = 'Magic Player Rewards'		 where code='pMPR';
update edition set goldfish_name = 'Arena Promos'				 where code='pARL';
update edition set goldfish_name = 'JSS MSS Promos'			   where code='pSUS';
update edition set goldfish_name = 'Conspiracy'				   where code='CNS';
update edition set goldfish_name = 'Prerelease Cards'			 where code='pPRE';
update edition set goldfish_name = 'Amonkhet Invocations'		 where code='MPS_AKH';


update edition set mkm_name = 'Junior Super Series Promos' where code = 'pSUS';
update edition set mkm_name = 'Player Rewards Promos'	  where code = 'pMPR';
update edition set mkm_name = 'Arena League Promos'		where code = 'pARL';


INSERT INTO card_keyword (keyword, fr ) values ('awaken',                   'eveil'),
INSERT INTO card_keyword (keyword, fr ) values ('battle cry',               'cri de guerre');
INSERT INTO card_keyword (keyword, fr ) values ('bestow',                   'grâce');
INSERT INTO card_keyword (keyword, fr ) values ('bloodrush',                'coup de sang');
INSERT INTO card_keyword (keyword, fr ) values ('bloodthirst',              'soif de sang');
INSERT INTO card_keyword (keyword, fr ) values ('bolster',                  'renforcement');
INSERT INTO card_keyword (keyword, fr ) values ('changeling',               'changelin');
INSERT INTO card_keyword (keyword, fr ) values ('clash',                    'confrontez');
INSERT INTO card_keyword (keyword, fr ) values ('constellation',            null);
INSERT INTO card_keyword (keyword, fr ) values ('convoke',                  'convocation');
INSERT INTO card_keyword (keyword, fr ) values ('converge',                 'convergence');
INSERT INTO card_keyword (keyword, fr ) values ('dash',                     'précipitation');
INSERT INTO card_keyword (keyword, fr ) values ('defender',                 'defenseur');
INSERT INTO card_keyword (keyword, fr ) values ('double strike',            'double initiative');
INSERT INTO card_keyword (keyword, fr ) values ('devoid',                   'carence');
INSERT INTO card_keyword (keyword, fr ) values ('devotion',                 'devotion');
INSERT INTO card_keyword (keyword, fr ) values ('delirium',                 'delire');
INSERT INTO card_keyword (keyword, fr ) values ('delve',                    'fouille');
INSERT INTO card_keyword (keyword, fr ) values ('evoke',                    null);
INSERT INTO card_keyword (keyword, fr ) values ('escalate',                 'intensification');
INSERT INTO card_keyword (keyword, fr ) values ('exalted',                  'exaltation');
INSERT INTO card_keyword (keyword, fr ) values ('exploit',                  'exploitation');
INSERT INTO card_keyword (keyword, fr ) values ('explores',                 'explore');
INSERT INTO card_keyword (keyword, fr ) values ('fabricate',                'fabrication');
INSERT INTO card_keyword (keyword, fr ) values ('ferocious',                'feocite');
INSERT INTO card_keyword (keyword, fr ) values ('flash',                    'flash');
INSERT INTO card_keyword (keyword, fr ) values ('flying',                   'vol');
INSERT INTO card_keyword (keyword, fr ) values ('formidable',               'redoutable');
INSERT INTO card_keyword (keyword, fr ) values ('forestwalk',               null);
INSERT INTO card_keyword (keyword, fr ) values ('haste',                    'celerite');
INSERT INTO card_keyword (keyword, fr ) values ('heroic',                   'heroique');
INSERT INTO card_keyword (keyword, fr ) values ('hexproof',                 'defense talismanique');
INSERT INTO card_keyword (keyword, fr ) values ('islandwalk',               'traversee des iles');
INSERT INTO card_keyword (keyword, fr ) values ('imprint',                  'empreinte');
INSERT INTO card_keyword (keyword, fr ) values ('improvise',                'improvisation');
INSERT INTO card_keyword (keyword, fr ) values ('ingest',                   'ingestion');
INSERT INTO card_keyword (keyword, fr ) values ('investigate',              'enqueter');
INSERT INTO card_keyword (keyword, fr ) values ('kicker',                   'kick');
INSERT INTO card_keyword (keyword, fr ) values ('landfall',                 'toucheterre');
INSERT INTO card_keyword (keyword, fr ) values ('lifelink',                 'lien de vie');
INSERT INTO card_keyword (keyword, fr ) values ('manifest',                 'manifestez');
INSERT INTO card_keyword (keyword, fr ) values ('madness',                  'folie');
INSERT INTO card_keyword (keyword, fr ) values ('megamorph',                'megamue');
INSERT INTO card_keyword (keyword, fr ) values ('meld',                     'assimilisation');
INSERT INTO card_keyword (keyword, fr ) values ('morph',                    'mue');
INSERT INTO card_keyword (keyword, fr ) values ('mountainwalk',             null);
INSERT INTO card_keyword (keyword, fr ) values ('outlast',                  'resilience');
INSERT INTO card_keyword (keyword, fr ) values ('plainswalk',               null);
INSERT INTO card_keyword (keyword, fr ) values ('prowess',                  'prouesse');
INSERT INTO card_keyword (keyword, fr ) values ('rally',                    'ralliement');
INSERT INTO card_keyword (keyword, fr ) values ('enrage',                   'rage');
INSERT INTO card_keyword (keyword, fr ) values ('reach',                    'portee');
INSERT INTO card_keyword (keyword, fr ) values ('renown',                   'reputation');
INSERT INTO card_keyword (keyword, fr ) values ('revolt',                   'revolte');
INSERT INTO card_keyword (keyword, fr ) values ('surge',                    'deferlement');
INSERT INTO card_keyword (keyword, fr ) values ('shroud',                   'linceul');
INSERT INTO card_keyword (keyword, fr ) values ('skulk',                    'furtivite');
INSERT INTO card_keyword (keyword, fr ) values ('snow-covered forestwalk',  null);
INSERT INTO card_keyword (keyword, fr ) values ('soulbond',                 'association d''ames');
INSERT INTO card_keyword (keyword, fr ) values ('spell mastery',            'maitrise de sort');
INSERT INTO card_keyword (keyword, fr ) values ('strike',                   'initiative');
INSERT INTO card_keyword (keyword, fr ) values ('strive',                   'obstination');
INSERT INTO card_keyword (keyword, fr ) values ('suspend',                  'suspension');
INSERT INTO card_keyword (keyword, fr ) values ('swampwalk',                null);
INSERT INTO card_keyword (keyword, fr ) values ('trample',                  'pietinement');
INSERT INTO card_keyword (keyword, fr ) values ('vigilance',                null);
